config/routes.rb
Jzcrm::Application.routes.draw do
  root :to => "dashboard#index"

  get "javascripts/city_mapper"

  match 'analytics/index' => 'analytics#index', :as => :analytics
  match 'dashboard' => 'dashboard#index', :as => :dashboard
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sources
  resources :reports
  resources :billboards
  resources :tasks
  resources :activities
  resources :notes
  resources :sessions
  resources :users
  resources :addresses
  resources :cities
  resources :provinces
  resources :line_items
  resources :orders
  resources :contacts
  resources :products
end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :name, :abbreviation

  has_many :cities
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  def index
    @provinces = Province.all
  end

  def show
    @province = Province.find(params[:id])
  end

  def new
    @province = Province.new
  end

  def create
    @province = Province.new(params[:province])
    if @province.save
      redirect_to @province, :notice => t('notice.create_successful')
    else
      render :action => 'new'
    end
  end

  def edit
    @province = Province.find(params[:id])
  end

  def update
    @province = Province.find(params[:id])
    if @province.update_attributes(params[:province])
      redirect_to @province, :notice  => "Successfully updated province."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @province = Province.find(params[:id])
    @province.destroy
    redirect_to provinces_url, :notice => t('notice.destroy_successful')
  end
end

app/views/provinces/_form.html.erb
<%= form_for @province do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/provinces/edit.html.erb
<% title "Edit Province" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @province %> |
  <%= link_to "View All", provinces_path %>
</p>

app/views/provinces/index.html.erb
<% title "Provinces" %>

<table>
  <tr>
    <th>Name</th>
    <th>Abbreviation</th>
  </tr>
  <% for province in @provinces %>
    <tr>
      <td><%= province.name %></td>
      <td><%= province.abbreviation %></td>
      <td><%= link_to "Show", province %></td>
      <td><%= link_to "Edit", edit_province_path(province) %></td>
      <td><%= link_to "Destroy", province, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Province", new_province_path %></p>

app/views/provinces/new.html.erb
<% title "New Province" %>

<%= render 'form' %>

<p><%= link_to "Back to List", provinces_path %></p>

app/views/provinces/show.html.erb
<% title "Province" %>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>
<p>
  <strong>Abbreviation:</strong>
  <%= @province.abbreviation %>
</p>

<p>
  <%= link_to "Edit", edit_province_path(@province) %> |
  <%= link_to "Destroy", @province, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", provinces_path %>
</p>