config/routes.rb
Jzcrm::Application.routes.draw do
  root :to => "dashboard#index"

  get "javascripts/city_mapper"

  match 'analytics/index' => 'analytics#index', :as => :analytics
  match 'dashboard' => 'dashboard#index', :as => :dashboard
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sources
  resources :reports
  resources :billboards
  resources :tasks
  resources :activities
  resources :notes
  resources :sessions
  resources :users
  resources :addresses
  resources :cities
  resources :provinces
  resources :line_items
  resources :orders
  resources :contacts
  resources :products
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :user_id, :topic_id, :topic_type, :subject_id, :subject_type, :action

  belongs_to :user
  belongs_to :topic, :polymorphic => true
  belongs_to :subject, :polymorphic => true

  scope :aggregate_for, lambda { |topic|
    case topic.class.to_s
    when "Contact"
      order_ids = %(SELECT id FROM orders WHERE contact_id = :topic_id)
      where("(topic_id IN (#{order_ids}) AND topic_type = 'Order') OR (topic_id = :topic_id AND topic_type = :topic_type)", { :topic_id => topic.id, :topic_type => topic.class.to_s })
    when "Order"
      where("(subject_id = :topic_id AND subject_type = :topic_type) OR (topic_id = :topic_id AND topic_type = :topic_type)", { :topic_id => topic.id, :topic_type => topic.class.to_s })
    else
      topic.activities.scoped
    end
  }

  def self.add(user, topic, subject, action=nil)
    self.create(
      :user_id => user.id,
      :topic_id => topic.id, :topic_type => topic.class.to_s,
      :subject_id => subject.id, :subject_type => subject.class.to_s,
      :action => action
    )
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :login_required

  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(params[:activity])
    if @activity.save
      redirect_to @activity, :notice => t('notice.create_successful')
    else
      render :action => 'new'
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(params[:activity])
      redirect_to @activity, :notice  => "Successfully updated activity."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_url, :notice => t('notice.destroy_successful')
  end
end

app/views/activities/_activity.html.erb
<div class="message<%= activity_counter == 0 ? " first" : "" %>">
  <%= render activity.subject, :activity => activity %>
</div>

app/views/activities/_form.html.erb
<%= form_for @activity do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :subject_id %><br />
    <%= f.text_field :subject_id %>
  </p>
  <p>
    <%= f.label :subject_type %><br />
    <%= f.text_field :subject_type %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/activities/edit.html.erb
<% title "Edit Activity" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @activity %> |
  <%= link_to "View All", activities_path %>
</p>

app/views/activities/index.html.erb
<% title "Activities" %>

<table>
  <tr>
    <th>User</th>
    <th>Subject</th>
    <th>Subject Type</th>
  </tr>
  <% for activity in @activities %>
    <tr>
      <td><%= activity.user_id %></td>
      <td><%= activity.subject_id %></td>
      <td><%= activity.subject_type %></td>
      <td><%= link_to "Show", activity %></td>
      <td><%= link_to "Edit", edit_activity_path(activity) %></td>
      <td><%= link_to "Destroy", activity, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Activity", new_activity_path %></p>

app/views/activities/new.html.erb
<% title "New Activity" %>

<%= render 'form' %>

<p><%= link_to "Back to List", activities_path %></p>

app/views/activities/show.html.erb
<% title "Activity" %>

<p>
  <strong>User:</strong>
  <%= @activity.user_id %>
</p>
<p>
  <strong>Subject:</strong>
  <%= @activity.subject_id %>
</p>
<p>
  <strong>Subject Type:</strong>
  <%= @activity.subject_type %>
</p>

<p>
  <%= link_to "Edit", edit_activity_path(@activity) %> |
  <%= link_to "Destroy", @activity, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", activities_path %>
</p>