config/routes.rb
Jzcrm::Application.routes.draw do
  root :to => "dashboard#index"

  get "javascripts/city_mapper"

  match 'analytics/index' => 'analytics#index', :as => :analytics
  match 'dashboard' => 'dashboard#index', :as => :dashboard
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sources
  resources :reports
  resources :billboards
  resources :tasks
  resources :activities
  resources :notes
  resources :sessions
  resources :users
  resources :addresses
  resources :cities
  resources :provinces
  resources :line_items
  resources :orders
  resources :contacts
  resources :products
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :title, :content, :user_id, :apply_to

  belongs_to :user
  belongs_to :applyee, :class_name => "User", :foreign_key => :apply_to
  has_many :notes, :as => :annotatable
  has_many :activities, :as => :topic

  validates_presence_of :title, :content, :apply_to
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :login_required

  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
    @note = @report.notes.build()
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(params[:report].merge(:user_id => current_user.id))
    if @report.save
      redirect_to @report, :notice => t('notice.create_successful')
    else
      render :action => 'new'
    end
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    params[:report].delete(:user_id) if params[:report] and params[:report][:user_id]
    if @report.update_attributes(params[:report])
      redirect_to @report, :notice  => t('notice.update_successful')
    else
      render :action => 'edit'
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to reports_url, :notice => t('notice.destroy_successful')
  end
end

app/views/reports/_form.html.erb
<%= form_for @report do |f| %>
  <%= f.error_messages %>

  <table>
    <tr>
      <td class="label"><%= f.label :title %></td>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <td class="label"><%= f.label :content %></td>
      <td><%= f.text_area :content %></td>
    </tr>
    <tr>
      <td class="label"><%= f.label :apply_to %></td>
      <td><%= f.collection_select :apply_to, User.options_for_select(:include_me => false), :id, :username, :include_blank => true %></td>
    </tr>
    <tr>
      <td>
      </td>
      <td>
        <%= f.submit t('.submit_report') %>
      </td>
    </tr>
  </table>
<% end %>

app/views/reports/edit.html.erb
<% title t('.edit_report'), false %>

<% content_for :header do %>
  <div class="buttons">
    <ul>
      <li><%= link_to t('.show'), @report %></li>
      <li><%= link_to t('.view_all'), reports_path %></li>
    </ul>
  </div>
  <h1><%= t('.edit_report') %></h1>
<% end %>

<div class="inner">
  <%= render 'form' %>
</div>

app/views/reports/index.html.erb
<% title t('.reports'), false %>

<% content_for :header do %>
  <div class="buttons">
    <ul>
      <li><%= link_to t('.new_report'), new_report_path %></li>
    </ul>
  </div>
  <h1><%= link_to t('.reports'), reports_path %></h1>
<% end %>

<div class="inner">
  <div class="listing">
    <% @reports.each_with_index do |report, index| %>
      <div class="item report<%= " first" if index == 0 %>">
        <div class="title">
          <%= link_to report.title, report %>
        </div>
        <div class="meta">
          <%= t('.before_user') %> <%= link_to report.user.username, report.user %> <%= t('.after_user') %>,
          <%= t('.applying_to') %> <%= link_to report.applyee.username, report.applyee %><br />
          <%= t('.at') %> <%= friendly_datetime(report.created_at) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/new.html.erb
<% title t('.new_report'), false %>

<% content_for :header do %>
  <div class="buttons">
    <ul>
      <li><%= link_to t('.back_to_list'), reports_path %></li>
    </ul>
  </div>
  <h1><%= t('.new_report') %></h1>
<% end %>

<div class="inner">
  <%= render 'form' %>
</div>

app/views/reports/show.html.erb
<% title t('.report'), false %>

<% content_for :header do %>
  <div class="buttons">
    <ul>
      <li><%= link_to t('.edit'), edit_report_path(@report) %></li>
      <li><%= link_to t('.destroy'), @report, :confirm => t('.are_you_sure'), :method => :delete %></li>
      <li><%= link_to t('.view_all'), reports_path %></li>
    </ul>
  </div>
  <h1><%= link_to t('.report'), reports_path %></h1>
<% end %>

<div class="inner">
  <div class="item report">
    <div class="title">
      <%= @report.title %>
    </div>
    <div class="meta">
      <%= t('.before_user') %> <%= link_to @report.user.username, @report.user %> <%= t('.after_user') %>,
      <%= t('.applying_to') %> <%= link_to @report.applyee.username, @report.applyee %><br />
      <%= t('.at') %> <%= friendly_datetime(@report.created_at) %>
    </div>
    <div class="content">
      <%= wrap(@report.content) %>
    </div>

    <% unless Activity.aggregate_for(@report).empty? %>
      <div id="messages">
        <%= render Activity.aggregate_for(@report).order('created_at') %>
      </div>
    <% end %>

    <div class="add_note">
      <h2><%= t('.add_a_new_note') %></h2>
      <div id="add_note_form">
        <%= render 'notes/form' %>
      </div>
    </div>
  </div>
</div>